<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Moser.RagAi.SeedPack</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Ingestion\Ingestion.Infrastructure\Ingestion.Infrastructure.csproj" />
  </ItemGroup>
</Project>
