<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Moser.RagAi.Ingestion.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="Microsoft.Bcl.Memory" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.ML.Tokenizers" />
    <PackageReference Include="Microsoft.ML.Tokenizers.Data.Cl100kBase" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Pgvector" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="UglyToad.PdfPig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ingestion.Application\Ingestion.Application.csproj" />
  </ItemGroup>

</Project>
