<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Moser.Enterprise.Blueprint.Catalog.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Microservices\Catalog\Catalog.Domain\Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\src\Microservices\Catalog\Catalog.Application\Catalog.Application.csproj" />
    <ProjectReference Include="..\..\src\Microservices\Catalog\Catalog.Infrastructure\Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Microservices\Catalog\Catalog.API\Catalog.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Unit\Domain\" />
    <Folder Include="Unit\Application\" />
    <Folder Include="Unit\Infrastructure\" />
    <Folder Include="Integration\API\" />
    <Folder Include="Integration\Infrastructure\" />
  </ItemGroup>

</Project>
