<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="EntityConfigurations\" />
    <Folder Include="Migrations\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\Catalog.Application\Catalog.Application.csproj" />
  </ItemGroup>

</Project>
